name: testing

on:
  merge_group:
    types: [checks_requested]
  workflow_call:
  pull_request:
  push:
    branches:
      - main

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  rust-testing:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-rust-testing
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-code-checking-${{ hashFiles('**/Cargo.lock') }}

      - name: run tests
        run: cargo test
